### PR TITLE
refactoring to use swiftmailer for email templating

### PR DESCRIPTION
**Pull request by chrisjohnson00**
This allows customization of the email templates sent for errors and non-error notices.
I also updated travis to get a full matrix of the supported php/symfony versions

### CODE REVIEW

**Comment by chrisjohnson00** [comment]
Travis fails on hhvm only, and the logs indicate a system issue rather than a code issue. Shall I move hhvm into the allowed failure list until it works again?

**Comment by chrisjohnson00** [comment]
travis continues to have issues... i'll bump the build again later in hopes that travis has restored network connectivity.  The new builds all failed at `composer update`

**Comment by chrisjohnson00** [comment]
woohoo.. Travis works again!  Let me know if you need anything else on this @J-Mose

**Comment by J-Mose** [comment]
Hi !

Very nice PR (sorry to only take a look at it now).

But with all new major releases, it seems not possible to add SwiftMailerBundle with PHP 5.6 and Symfony 3.4 (All SwiftMailerBundle Sf3.4 compat require php 7)

I'll probably integrate SwiftMailer when droping PHP 5.6.

**Comment by chrisjohnson00** [comment]
sounds good, let me know if there's anything required from me on this.  I'm happy to help.

**Comment by chrisjohnson00** [comment]
if i get a chance, i'll see if there's any changes I can make to the composer dependency versions, as this _should_ be usable with PHP 5.6
https://packagist.org/packages/symfony/swiftmailer-bundle#v2.3.10 shows that it requires `>=5.3.2`, while swiftmailer itself requires `>=5.3.3`

**Pull request closed without merging**
