### PR TITLE
Add support for Symfony 5

### PR DESCRIPTION
**Pull request by spajxo**
Hi,

added support for symfony 5.0 components.

#SymfonyHackday

### CODE REVIEW

**Comment by spajxo** [comment]
Looks like the test doesn't pass because of composer constraints in liip/functional-test-bundle.

**Comment by j-guyon** [comment]
Just make some tests with liip/functional-test-bundle is available @3.4-alpha1, i will dig more with the non alpha/beta release. This will be probably on a major release which will have to deal with php 7.2 too.

**Comment by alex8444** [comment]
it looks like it's still not possible to use it with symfony 5.x

**Comment by Gemineye** [comment]
Any news here? Is it working with liip/functional-test-bundle 4.1?

**Comment by spajxo** [comment]
Hi, 

sorry, but i am currently not in the position to have time to work on this.

If anyone wants to take over, feel free to do so.

**Comment by SimonHeimberg** [comment]
this would fix #146

**Comment by spajxo** [comment]
Hello everyone. 

I managed to fix all funcitonal tests.
I bumped version of liip/functional-test-bundle to ^4.2 and phpunit to ^8.5.

Don't know why, but travis doesn't seem to be running.

**Comment by spajxo** [comment]
I set up travis on my fork
https://travis-ci.org/github/spajxo/CommandSchedulerBundle/builds/697750106

Had to modify travis config a little, and remove typehint on BaseController::setTranslator()

Now it is working for all combinations :+1:

**Comment by Voltisky** [comment]
I'm waiting on it 👍

**Comment by gisostallenberg** [comment]
> I'm waiting on it

Yes, me too :smiley:

**Pull request merged**
